### ISSUE TITLE
pixiecore doesn't cooperate with running dnsmasq on the same server

### ISSUE THREAD

**Issue by abitrolly** [google/netboot#45]
`pixiecore` doesn't cooperate with running `dnsmasq` like said here:

https://github.com/google/netboot/blob/792915a85f22dd96794e94c7732170c8e7620a2b/pixiecore/README.md#L18

```
$ sudo pixiecore quick ubuntu zesty
listen udp4 :67: bind: address already in use
$ sudo netstat -aunp | grep 67
udp        0      0 0.0.0.0:67              0.0.0.0:*                           11605/dnsmasq   
udp        0      0 0.0.0.0:67              0.0.0.0:*                           10754/dnsmasq   
```

**Comment by danderson** [comment]
That's correct, Pixiecore needs to listen on the DHCP server port, the same as dnsmasq. This is a consequence of how DHCP works.

Fortunately, there's a flag for that! On linux, you should be able to pass --dhcp-no-bind to make this work. With this flag, Pixiecore will use the kernel's raw packet facilities (similar to how tcpdump operates) to read/write DHCP packets to the network without binding to :67.

This behavior is not enabled by default because it can be very confusing (e.g. netstat doesn't show pixiecore listening on :67, even though it's receiving/sending traffic on that port), and it only works on linux currently. But, it was implemented specifically for your use case.

**Comment by abitrolly** [comment]
Thanks. This worked for me:
```
sudo pixiecore quick ubuntu zesty --dhcp-no-bind
```
