### ISSUE TITLE
go.universe.tf is dead

### ISSUE THREAD

**Issue by faddat** [google/netboot#48]
go.universe.tf is down, and so pixiecore doesn't build.

**Comment by danderson** [comment]
Argh. Thanks for the report. Turns out hosting go.universe.tf has increased traffic to the domain enough that I ran out of free quota on buddyns.com.

I've hit the buttons to fix the problem (by migrating back to Gandi, which doesn't do per-query quotas), but because of DNS propagation times, it'll take 12-24h before the domain is back up :(.

In the meantime, you can clone https://github.com/google/netboot into $GOPATH/src/go.universe.tf/netboot , as a workaround.

Sorry for the disruption. Once the DNS migration is done there shouldn't be any more issues like this.

**Comment by danderson** [comment]
go.universe.tf is resolving again on my system, so at least some parts of the internet have synced to the updated NS records. Can you verify, and close if it works for you?

**Comment by faddat** [comment]
Sure, checking right now!
